### ISSUE TITLE
gulp task release:full should use inquirer

### ISSUE THREAD

**Issue by thaiat** [thaiat/generator-sublime#154]
We should use `inquirer` package in gulp `release:full` to ask for username and password instead of options.

Also username should be easy to get, without asking the end user, using the npm package `github-username`

for using `github-username` see:
https://github.com/yeoman/generator/blob/master/lib/actions/user.js

for password (hiding the password) see:  https://github.com/SBoudrias/Inquirer.js/blob/81c4235919b2f6719a34cb05b30d272966683e7d/examples/password.js

Tasks:
- [x] Retreive username with `github-username`    
- [x] Ask password with `inquirer`
- [x] Modify actual tasks (instead of templates) in this project
- [x] Modify task in gulp-mux
- [x] Modify task in generator-angular-famous-ionic

**Comment by jskrzypek** [comment]
Tackling this now

**Comment by jskrzypek** [comment]
The [`github`](http://npmjs.org/package/github) module we're already using in release allows us to [search and retrieve](http://mikedeboer.github.io/node-github/#search.prototype.users) the github username like `github-username` does. 

It's a pretty simple call:
```js
github.search.users({q: 'jskrzypek@gmail.com in:email'}, function(err, res) {
    /* do stuff */
    );
```

**Comment by jskrzypek** [comment]
Check out working refactor in gulp task [`githubAuth`](https://github.com/thaiat/generator-sublime/blob/feat-release-inquirer/gulp_tasks/tasks/release.js#L131) on branch [`feat-release-inquirer`](https://github.com/thaiat/generator-sublime/tree/feat-release-inquirer).

**Comment by thaiat** [comment]
you don t need to ask for username or email

the info is in git config

Le lundi 19 janvier 2015, Joshua Skrzypek <notifications@github.com> a
écrit :
